### ISSUE TITLE
Modules in https://gitlab.gnome.org/World

### ISSUE THREAD

**Issue by rffontenelle** [Malizor/deckard#10]
`build-gnome-module.sh` knows only https://gitlab.gnome.org/GNOME, but some extra apps are stored in https://gitlab.gnome.org/World. That includes [fractal](https://gitlab.gnome.org/World/fractal), [PasswordSafe](https://gitlab.gnome.org/World/PasswordSafe) and [podcasts](https://gitlab.gnome.org/World/podcasts).

Please make possible to include modules from World group and also include the three mentioned above.

**Comment by Malizor** [comment]
Hi and thank you for the report.

Reworking `build-gnome-module.sh` would indeed be nice, not only because of the `/World` projects but also because it could be more clever and use the Gitlab API to list all available projects instead of hardcoding a project list directly into the script.

I started a proof of concept of a brand new script in Python, but it turned out to be more complicated than anticipated. Now my next goal (once I'm back from holidays…) is to try to adapt the existing `build-gnome-module.sh` to do  this.
Also the problem that I encountered is that gitlab.gnome.org is quite slow, so regularly cloning all available projects to analyze if anything from it is displayable into Deckard may be a bit tricky. Some discussions with the GNOME sysadmin may be needed.

Meanwhile, if you need a particular `/World` project to be added into Deckard, please create dedicated issues as this can be done in a "quick and dirty" way with minimal changes to the existing script.

**Comment by rffontenelle** [comment]
Damned Lies now has a beta version of Rest API which eases finding out GNOME modules that allow localization. I'm reworking my own scripts, and I found two command lines that helped me getting URL of all translated modules (which in my case included non-GNOME modules as well)

1- API URL of all modules
`apiurl=$(curl https://l10n.gnome.org/api/v1/modules/ | jq | grep href | cut -d\" -f4)`

2- For each API URL of the above modules, check its `cvs_root`:
```
for mod in $apiurl; do
    modcvsroot=$(curl https://l10n.gnome.org/api/v1/modules/$modurlapi | jq | grep vcs_root | cut -d\" -f4)
done
```

See Claude's announce on the D-L API https://mail.gnome.org/archives/gnome-i18n/2019-January/msg00018.html

**Comment by Malizor** [comment]
Thanks for the tip, that sound promising! I will definitely have a look.

As a side note, you can use `jq` to parse the json directly, like this:
`apiurl=$(curl https://l10n.gnome.org/api/v1/modules/ | jq -r .[].href)`

**Comment by Malizor** [comment]
I opened the following tickets again Damned Lies:
https://gitlab.gnome.org/Infrastructure/damned-lies/issues/121
https://gitlab.gnome.org/Infrastructure/damned-lies/issues/122

**Comment by Malizor** [comment]
This was implemented in the `build-gnome-contentv2` branch. It's going to run on https://deckard.malizor.org with tonight update. I will merge it in `master` tomorrow if everything works as planned.

**Comment by Malizor** [comment]
Some improvements still need to be made, as some of the new UIs trigger 502 errors in deckard.
But it can be seen later. So let's consider this fixed! :)

**Comment by rffontenelle** [comment]
That's awesome! Thanks a lot!
