### ISSUE TITLE
GNOME Connections

### ISSUE THREAD

**Issue by rffontenelle** [Malizor/deckard#15]
I didn't find [GNOME Connections](gitlab.gnome.org/GNOME/connections) listed in deckard's dropdown menu neither blacklisted in build-gnome-content.sh. Can you please verify if it can be rendered in Deckard? Thanks in advance.

**Comment by Malizor** [comment]
I think this is because the damned lies API contains an invalid "vcs_web" link for this module (a git address instead of the gitlab web address)
https://l10n.gnome.org/api/v1/modules/gnome-connections

This may confuse build-gnome-content.sh when it tries to retrieve the module.
Now I don't know if this is a widespread error on DL, so if it's better to handle this case in build-gnome-content.sh or if all such errors should be reported and fixed upstream.
I will look at this again later.

**Comment by rffontenelle** [comment]
Thanks for the reply. Maybe you should have `web_url=$(echo $web_url | sed 's|/$|.git|')` in [build-gnome-content.sh lien 362](https://github.com/Malizor/deckard/blob/master/build-gnome-content.sh#L362), to avoid issues with ".git" in vcs_web

**Comment by Malizor** [comment]
That's the idea, except that sometime these URLs do not have a trailing slash.

Anyway I reported the wrong URL upstream and it was fixed immediately: https://gitlab.gnome.org/Infrastructure/damned-lies/-/issues/243

I browsed the other modules and Gnome Connections was the only faulty one.  
So this means there is no more workaround needed on the Deckard side regarding this issue.

An actual fix was needed in build-gnome-content.sh however, to handle this module name difference between Gitlab and Damned Lies (ie. `connections` vs `gnome-connections`).  
Apparently this fix was also needed for projects like Authenticator, Fragments, Shortwave, Social or Solanum so that's good news.

I relaunched build-gnome-content.sh manually on the server and now gnome-connections (as well as the above modules) are available on Deckard:
https://deckard.malizor.org/?module=gnome-connections

So that's all fixed!  
There are some 502 errors on some UI files but this is for another ticket.

Thanks for the report!
