### ISSUE TITLE
giara .ui files trigger 502 bad gateway

### ISSUE THREAD

**Issue by dasj19** [Malizor/deckard#16]
Choosing the following two .ui files result in a server error:
https://deckard.malizor.org/?module=giara&ui=data/ui/comment_box.ui&locale=POSIX&display=1
https://deckard.malizor.org/?module=giara&ui=data/ui/main_ui.ui&locale=POSIX&display=1

Server responds with: 502 Bad Gateway

**Comment by Malizor** [comment]
Hi and thanks for the report.

In my investigation so far I see two problems:
* The preview process crashes with a core-dump. Those two .ui files use the `GtkRevealer` which seems to be the cause of this.
* Since the process crashes, those .ui files should actually not event be selectable. So there is a bug in the update script also.

Further investigation is needed, I will have a look later.
